name: Test Reporter

description: |
  Parses various code coverage report formats (Clover, Cobertura,
  JaCoCo, LCOV) to generate a detailed summary with progress bars
  and file-specific links directly in your GitHub Actions workflow.

author: mridang
branding:
  color: blue

inputs:
  github-token:
    description: >
      GitHub token used to authenticate API requests. Required for
      checking status checks and publishing releases. Use
      `secrets.GITHUB_TOKEN` or a PAT with elevated scopes if needed.
    required: true

  working-directory:
    description: >
      The directory where your project is located, used as the base for
      making file paths in the report relative.
    required: false
    default: '.'

  coverage-file:
    description: >
      The path to the single code coverage report file you want to parse
      (e.g., 'build/reports/clover.xml').
    required: true

  upload-coverage-report:
    description: >
      Set to `true` to upload the generated coverage report as a workflow
      artifact. If omitted or left empty, this defaults to `true`.
      Set to `false` to disable artifact upload.
    required: false
    default: 'true'

runs:
  using: node20
  main: dist/main.cjs
